SELECT /*+ PARALLEL(AUTO) */
  NULL AS CONSTRAINT_CATALOG,
  CHECK_CONSTRAINTS.OWNER AS CONSTRAINT_SCHEMA,
  CHECK_CONSTRAINTS.CONSTRAINT_NAME,
  DBMS_METADATA.GET_DDL('CONSTRAINT', CHECK_CONSTRAINTS.CONSTRAINT_NAME, CHECK_CONSTRAINTS.OWNER) 
    AS CHECK_CLAUSE
FROM
  ALL_CONSTRAINTS CHECK_CONSTRAINTS
WHERE
  CHECK_CONSTRAINTS.OWNER NOT IN 
    ('ANONYMOUS', 'APEX_PUBLIC_USER', 'APPQOSSYS', 'BI', 'CTXSYS', 'DBSNMP', 'DIP', 
    'EXFSYS', 'FLOWS_30000', 'FLOWS_FILES', 'HR', 'IX', 'LBACSYS', 
    'MDDATA', 'MDSYS', 'MGMT_VIEW', 'OE', 'OLAPSYS', 'ORACLE_OCM', 
    'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'OWBSYS', 'PM', 'SCOTT', 'SH', 
    'SI_INFORMTN_SCHEMA', 'SPATIAL_CSW_ADMIN_USR', 'SPATIAL_WFS_ADMIN_USR', 
    'SYS', 'SYSMAN', 'SYSTEM', 'TSMSYS', 'WKPROXY', 'WKSYS', 'WK_TEST', 
    'WMSYS', 'XDB', 'XS$NULL', 'RDSADMIN')  
  AND NOT REGEXP_LIKE(CHECK_CONSTRAINTS.OWNER, '^APEX_[0-9]{6}$')
  AND NOT REGEXP_LIKE(CHECK_CONSTRAINTS.OWNER, '^FLOWS_[0-9]{5,6}$')
  AND REGEXP_LIKE(CHECK_CONSTRAINTS.OWNER, '${schemas}')
  AND CHECK_CONSTRAINTS.TABLE_NAME NOT LIKE 'BIN$%'
  AND CONSTRAINT_TYPE = 'C'
