SELECT /*+ PARALLEL(AUTO) */
  NULL AS INDEX_CATALOG,
  INDEXES.OWNER AS INDEX_SCHEMA,
  INDEXES.INDEX_NAME AS INDEX_NAME,
  INDEXES.TABLE_NAME AS TABLE_NAME,
  CASE WHEN INDEXES.UNIQUENESS = 'UNIQUE' THEN 'YES' ELSE 'NO' END AS IS_UNIQUE,
  DBMS_METADATA.GET_DDL('INDEX', INDEXES.INDEX_NAME, INDEXES.OWNER) AS INDEX_DEFINITION
FROM
  ALL_INDEXES INDEXES
  INNER JOIN ALL_USERS USERS
    ON INDEXES.OWNER = USERS.USERNAME
WHERE
  USERS.ORACLE_MAINTAINED != 'Y'
  AND NOT REGEXP_LIKE(USERS.USERNAME, '^APEX_[0-9]{6}$')
  AND NOT REGEXP_LIKE(USERS.USERNAME, '^FLOWS_[0-9]{6}$')
  AND NOT REGEXP_LIKE(USERS.USERNAME, '^FLOWS_[0-9]{5}$')
  AND INDEXES.TABLE_NAME NOT LIKE 'BIN$%'
ORDER BY
  INDEX_SCHEMA,
  TABLE_NAME,
  INDEX_NAME
