SELECT /*+ PARALLEL(AUTO) */
  NULL AS FOREIGN_KEY_CATALOG,
  FOREIGN_KEYS.OWNER AS FOREIGN_KEY_SCHEMA,
  FOREIGN_KEYS.TABLE_NAME AS FOREIGN_KEY_TABLE_NAME,  
  FOREIGN_KEYS.CONSTRAINT_NAME AS FOREIGN_KEY_NAME,
  DBMS_METADATA.GET_DDL('REF_CONSTRAINT', FOREIGN_KEYS.CONSTRAINT_NAME, FOREIGN_KEYS.OWNER) 
    AS FOREIGN_KEY_DEFINITION
FROM
  ALL_CONSTRAINTS FOREIGN_KEYS
WHERE
  FOREIGN_KEYS.OWNER NOT IN 
    ('ANONYMOUS', 'APEX_PUBLIC_USER', 'APPQOSSYS', 'BI', 'CTXSYS', 'DBSNMP', 'DIP', 
    'EXFSYS', 'FLOWS_30000', 'FLOWS_FILES', 'HR', 'IX', 'LBACSYS', 
    'MDDATA', 'MDSYS', 'MGMT_VIEW', 'OE', 'OLAPSYS', 'ORACLE_OCM', 
    'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'OWBSYS', 'PM', 'SCOTT', 'SH', 
    'SI_INFORMTN_SCHEMA', 'SPATIAL_CSW_ADMIN_USR', 'SPATIAL_WFS_ADMIN_USR', 
    'SYS', 'SYSMAN', 'SYSTEM', 'TSMSYS', 'WKPROXY', 'WKSYS', 'WK_TEST', 
    'WMSYS', 'XDB', 'XS$NULL', 'RDSADMIN')  
  AND NOT REGEXP_LIKE(FOREIGN_KEYS.OWNER, '^APEX_[0-9]{6}$')
  AND NOT REGEXP_LIKE(FOREIGN_KEYS.OWNER, '^FLOWS_[0-9]{5,6}$')
  AND REGEXP_LIKE(FOREIGN_KEYS.OWNER, '${schemas}')
  AND FOREIGN_KEYS.TABLE_NAME NOT LIKE 'BIN$%'
  AND FOREIGN_KEYS.CONSTRAINT_TYPE = 'R'
