SELECT /*+ PARALLEL(AUTO) */
  NULL AS SYNONYM_CATALOG,
  OWNER AS SYNONYM_SCHEMA,
  SYNONYM_NAME,
  NULL AS REFERENCED_OBJECT_CATALOG,
  TABLE_OWNER AS REFERENCED_OBJECT_SCHEMA,
  TABLE_NAME AS REFERENCED_OBJECT_NAME
FROM
  ALL_SYNONYMS
WHERE
  OWNER NOT IN ('ANONYMOUS','APEX_PUBLIC_USER','CTXSYS','DBSNMP','DIP','EXFSYS','FLOWS_%','FLOWS_FILES','LBACSYS','MDDATA','MDSYS','MGMT_VIEW','OLAPSYS','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OUTLN','OWBSYS','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','SYS','SYSMAN','SYSTEM','WKPROXY','WKSYS','WK_TEST','WMSYS','XDB','XS$NULL')
  AND OWNER NOT LIKE 'APEX%'
