SELECT /*+ PARALLEL(AUTO) */
  NULL AS CONSTRAINT_CATALOG,
  OWNER AS CONSTRAINT_SCHEMA,
  CONSTRAINT_NAME,
  NULL AS TABLE_CATALOG,
  OWNER AS TABLE_SCHEMA,
  TABLE_NAME,
  CASE CONSTRAINT_TYPE WHEN 'C' THEN 'CHECK' WHEN 'U' THEN 'UNIQUE' WHEN 'P' THEN 'PRIMARY KEY' WHEN 'R' THEN 'FOREIGN KEY' END AS CONSTRAINT_TYPE,
  CASE WHEN DEFERRABLE = 'NOT DEFERRABLE' THEN 'N' ELSE 'Y' END AS IS_DEFERRABLE,
  CASE WHEN DEFERRED = 'IMMEDIATE' THEN 'N' ELSE 'Y' END AS INITIALLY_DEFERRED
FROM
  ALL_CONSTRAINTS
WHERE
  OWNER NOT IN ('ANONYMOUS','APEX_PUBLIC_USER','CTXSYS','DBSNMP','DIP','EXFSYS','FLOWS_%','FLOWS_FILES','LBACSYS','MDDATA','MDSYS','MGMT_VIEW','OLAPSYS','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OUTLN','OWBSYS','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','SYS','SYSMAN','SYSTEM','WKPROXY','WKSYS','WK_TEST','WMSYS','XDB','XS$NULL')
  AND OWNER NOT LIKE 'APEX%'
  AND TABLE_NAME NOT LIKE 'BIN$%'
  AND CONSTRAINT_TYPE IN ('C', 'U', 'P', 'R')
