SELECT  
  NULL AS TABLE_CAT,
  TABLES.OWNER AS TABLE_SCHEM,
  TABLES.TABLE_NAME AS TABLE_NAME,
  TABLES.TABLE_TYPE AS TABLE_TYPE,
  TABLES.COMMENTS AS REMARKS
FROM 
  ${catalogscope}_TAB_COMMENTS TABLES
WHERE
  TABLES.OWNER NOT IN 
    ('ANONYMOUS', 'APEX_PUBLIC_USER', 'APPQOSSYS', 'AUDSYS', 'BI', 'CTXSYS', 'DBSNMP', 'DIP', 
    'DVF', 'DVSYS', 'EXFSYS', 'FLOWS_30000', 'FLOWS_FILES', 'GSMADMIN_INTERNAL', 'HR', 'IX', 
    'LBACSYS', 'MDDATA', 'MDSYS', 'MGMT_VIEW', 'OE', 'OLAPSYS', 'ORACLE_OCM', 'ORDPLUGINS', 
    'ORDSYS', 'OUTLN', 'OWBSYS', 'PM', 'RDSADMIN', 'SCOTT', 'SH', 'SI_INFORMTN_SCHEMA', 
    'SPATIAL_CSW_ADMIN_USR', 'SPATIAL_WFS_ADMIN_USR', 'SYS', 'SYSMAN', 'TSMSYS', 'WKPROXY', 
    'WKSYS', 'WK_TEST', 'WMSYS', 'XDB', 'XS$NULL', 'SYSTEM')
  AND NOT REGEXP_LIKE(TABLES.OWNER, '^APEX_[0-9]{6}$')
  AND NOT REGEXP_LIKE(TABLES.OWNER, '^FLOWS_[0-9]{5,6}$')
  AND REGEXP_LIKE(TABLES.OWNER, '${schemas}')
  AND TABLES.TABLE_NAME NOT LIKE 'BIN$%'
  AND NOT REGEXP_LIKE(TABLES.TABLE_NAME, '^(SYS_IOT|MDOS|MDRS|MDRT|MDOT|MDXT)_.*$')
UNION ALL
SELECT  
  NULL AS TABLE_CAT,
  MVIEWS.OWNER AS TABLE_SCHEM,
  MVIEWS.MVIEW_NAME AS TABLE_NAME,
  'MATERIALIZED VIEW' AS TABLE_TYPE,
  MVIEWS.COMMENTS AS REMARKS
FROM 
  ${catalogscope}_MVIEW_COMMENTS MVIEWS
WHERE
  MVIEWS.OWNER NOT IN 
    ('ANONYMOUS', 'APEX_PUBLIC_USER', 'APPQOSSYS', 'AUDSYS', 'BI', 'CTXSYS', 'DBSNMP', 'DIP', 
    'DVF', 'DVSYS', 'EXFSYS', 'FLOWS_30000', 'FLOWS_FILES', 'GSMADMIN_INTERNAL', 'HR', 'IX', 
    'LBACSYS', 'MDDATA', 'MDSYS', 'MGMT_VIEW', 'OE', 'OLAPSYS', 'ORACLE_OCM', 'ORDPLUGINS', 
    'ORDSYS', 'OUTLN', 'OWBSYS', 'PM', 'RDSADMIN', 'SCOTT', 'SH', 'SI_INFORMTN_SCHEMA', 
    'SPATIAL_CSW_ADMIN_USR', 'SPATIAL_WFS_ADMIN_USR', 'SYS', 'SYSMAN', 'TSMSYS', 'WKPROXY', 
    'WKSYS', 'WK_TEST', 'WMSYS', 'XDB', 'XS$NULL', 'SYSTEM')
  AND NOT REGEXP_LIKE(MVIEWS.OWNER, '^APEX_[0-9]{6}$')
  AND NOT REGEXP_LIKE(MVIEWS.OWNER, '^FLOWS_[0-9]{5,6}$')
  AND REGEXP_LIKE(MVIEWS.OWNER, '${schemas}')
