-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2025, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

SELECT
 'NUMBER' AS TYPE_NAME, 2 AS DATA_TYPE, 38 AS PRECISION,
 NULL AS LITERAL_PREFIX, NULL AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 1 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'NUMBER' AS LOCAL_TYPE_NAME, -84 AS MINIMUM_SCALE, 127 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'CHAR' AS TYPE_NAME, 1 AS DATA_TYPE, 2000 AS PRECISION,
 '''' AS LITERAL_PREFIX, '''' AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 1 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'CHAR' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'VARCHAR2' AS TYPE_NAME, 12 AS DATA_TYPE, 4000 AS PRECISION,
 '''' AS LITERAL_PREFIX, '''' AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 1 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'VARCHAR2' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'DATE' AS TYPE_NAME, 91 AS DATA_TYPE, 7 AS PRECISION,
 NULL AS LITERAL_PREFIX, NULL AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'DATE' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'TIMESTAMP' AS TYPE_NAME, 93 AS DATA_TYPE, 11 AS PRECISION,
 NULL AS LITERAL_PREFIX, NULL AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'TIMESTAMP' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'TIMESTAMP WITH TIME ZONE' AS TYPE_NAME, -101 AS DATA_TYPE, 13 AS PRECISION,
 NULL AS LITERAL_PREFIX, NULL AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'TIMESTAMP WITH TIME ZONE' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'TIMESTAMP WITH LOCAL TIME ZONE' AS TYPE_NAME, -102 AS DATA_TYPE, 11 AS PRECISION,
 NULL AS LITERAL_PREFIX, NULL AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'TIMESTAMP WITH LOCAL TIME ZONE' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'INTERVALYM' AS TYPE_NAME, -103 AS DATA_TYPE, 5 AS PRECISION,
 NULL AS LITERAL_PREFIX, NULL AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'INTERVALYM' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'INTERVALDS' AS TYPE_NAME, -104 AS DATA_TYPE, 4 AS PRECISION,
 NULL AS LITERAL_PREFIX, NULL AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'INTERVALDS' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'RAW' AS TYPE_NAME, -3 AS DATA_TYPE, 2000 AS PRECISION,
 '''' AS LITERAL_PREFIX, '''' AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'RAW' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'LONG' AS TYPE_NAME, -1 AS DATA_TYPE, 2147483647 AS PRECISION,
 '''' AS LITERAL_PREFIX, '''' AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 1 AS CASE_SENSITIVE, 0 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'LONG' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'LONG RAW' AS TYPE_NAME, -4 AS DATA_TYPE, 2147483647 AS PRECISION,
 '''' AS LITERAL_PREFIX, '''' AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 0 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'LONG RAW' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT 'FLOAT' AS TYPE_NAME, 6 AS DATA_TYPE, 63 AS PRECISION,
NULL AS LITERAL_PREFIX, NULL AS LITERAL_SUFFIX,
NULL AS CREATE_PARAMS, 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
0 AS UNSIGNED_ATTRIBUTE, 1 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
'FLOAT' AS LOCAL_TYPE_NAME, -84 AS MINIMUM_SCALE, 127 AS MAXIMUM_SCALE,
NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT 'REAL' AS TYPE_NAME, 7 AS DATA_TYPE, 63 AS PRECISION,
NULL AS LITERAL_PREFIX, NULL AS LITERAL_SUFFIX,
NULL AS CREATE_PARAMS, 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 3 AS SEARCHABLE,
0 AS UNSIGNED_ATTRIBUTE, 1 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
'REAL' AS LOCAL_TYPE_NAME, -84 AS MINIMUM_SCALE, 127 AS MAXIMUM_SCALE,
NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'BLOB' AS TYPE_NAME, 2004 AS DATA_TYPE, -1 AS PRECISION,
 NULL AS LITERAL_PREFIX, NULL AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 0 AS CASE_SENSITIVE, 0 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'BLOB' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'CLOB' AS TYPE_NAME, 2005 AS DATA_TYPE, -1 AS PRECISION,
 '''' AS LITERAL_PREFIX, '''' AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 1 AS CASE_SENSITIVE, 0 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'CLOB' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'REF' AS TYPE_NAME, 2006 AS DATA_TYPE, 0 AS PRECISION,
 '''' AS LITERAL_PREFIX, '''' AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 1 AS CASE_SENSITIVE, 0 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'REF' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'ARRAY' AS TYPE_NAME, 2003 AS DATA_TYPE, 0 AS PRECISION,
 '''' AS LITERAL_PREFIX, '''' AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 1 AS CASE_SENSITIVE, 0 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'ARRAY' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
UNION ALL
SELECT
 'STRUCT' AS TYPE_NAME, 2002 AS DATA_TYPE, 0 AS PRECISION,
 '''' AS LITERAL_PREFIX, '''' AS LITERAL_SUFFIX, NULL AS CREATE_PARAMS,
 1 AS NULLABLE, 1 AS CASE_SENSITIVE, 0 AS SEARCHABLE,
 0 AS UNSIGNED_ATTRIBUTE, 0 AS FIXED_PREC_SCALE, 0 AS AUTO_INCREMENT,
 'STRUCT' AS LOCAL_TYPE_NAME, 0 AS MINIMUM_SCALE, 0 AS MAXIMUM_SCALE,
 NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, 10 AS NUM_PREC_RADIX
FROM DUAL
ORDER BY
  DATA_TYPE
