SELECT /*+ PARALLEL(AUTO) */
  NULL AS TABLE_CATALOG,
  OWNER AS TABLE_SCHEMA,
  VIEW_NAME AS TABLE_NAME,
  TEXT AS VIEW_DEFINITION,
  'UNKNOWN' AS CHECK_OPTION,
  CASE WHEN READ_ONLY = 'N' THEN 'Y' ELSE 'N' END AS IS_UPDATABLE
FROM
  ALL_VIEWS
WHERE
  OWNER NOT IN ('ANONYMOUS','APEX_PUBLIC_USER','CTXSYS','DBSNMP','DIP','EXFSYS','FLOWS_%','FLOWS_FILES','LBACSYS','MDDATA','MDSYS','MGMT_VIEW','OLAPSYS','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OUTLN','OWBSYS','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','SYS','SYSMAN','SYSTEM','WKPROXY','WKSYS','WK_TEST','WMSYS','XDB','XS$NULL')
  AND OWNER NOT LIKE 'APEX%'
ORDER BY
  TABLE_SCHEMA,
  TABLE_NAME
