CREATE USER ~USER~ IDENTIFIED BY ~USER~;
GRANT CONNECT TO ~USER~;
GRANT UNLIMITED TABLESPACE TO ~USER~;
GRANT CREATE MATERIALIZED VIEW TO ~USER~;
GRANT QUERY REWRITE TO ~USER~;
GRANT CREATE ANY TABLE TO ~USER~;
ALTER SESSION SET CURRENT_SCHEMA = ~USER~;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
