CREATE TABLE GUY 
(
  ID VARCHAR2(255) PRIMARY KEY,
  NAME VARCHAR2(255) NOT NULL,
  FAVOURITE_VOWEL VARCHAR2(1) NOT NULL 
    CHECK (FAVOURITE_VOWEL IN ('A', 'E', 'I', 'O', 'U', 'Y'))
)
;

CREATE INDEX NAME_INDEX ON GUY (NAME)
;
