version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      # Apache Hive JDBC supports Java 21 from v4.2.0 onwards
      - dependency-name: "org.apache.hive:hive-jdbc"
        update-types: ["version-update:semver-minor"]
      # 15.x Informix drivers are not well-behaved
      - dependency-name: "com.ibm.informix:jdbc"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
    assignees:
      - "sualeh"
      - "schemacrawler"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    assignees:
      - sualeh
      - schemacrawler
