CREATE DATABASE IF NOT EXISTS BOOKS;
CREATE SCHEMA IF NOT EXISTS BOOKS.BOOKS;

CREATE TABLE IF NOT EXISTS BOOKS.BOOKS.AUTHORS
(
  ID INTEGER,
  FIRSTNAME VARCHAR,
  LASTNAME VARCHAR
);

INSERT INTO BOOKS.BOOKS.AUTHORS
  (ID, FIRSTNAME, LASTNAME)
VALUES
  (1, 'Jane', 'Austen');
