SELECT
  NULLIF(1, 1) AS TABLE_CATALOG,
  LTRIM(RTRIM(SYSCAT.TABLES.TABSCHEMA)) AS TABLE_SCHEMA,
  LTRIM(RTRIM(SYSCAT.TABLES.TABNAME)) AS TABLE_NAME,
  SYSCAT.TABLES.CREATE_TIME,
  SYSCAT.TABLES.ALTER_TIME,
  LTRIM(RTRIM(SYSCAT.TABLESPACES.TBSPACE)) AS TABLE_SPACE
FROM
  SYSCAT.TABLES
  INNER JOIN SYSCAT.TABLESPACES
    ON SYSCAT.TABLES.TBSPACEID = SYSCAT.TABLESPACES.TBSPACEID
WITH UR
