-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2026, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

SELECT
  NULLIF(1, 1) AS CONSTRAINT_CATALOG,
  STRIP(SYSCAT.CHECKS.TABSCHEMA) AS CONSTRAINT_SCHEMA,
  STRIP(SYSCAT.CHECKS.CONSTNAME) AS CONSTRAINT_NAME,
  SYSCAT.CHECKS.TEXT AS CHECK_CLAUSE
FROM
  SYSCAT.CHECKS
ORDER BY
  SYSCAT.CHECKS.TABSCHEMA,
  SYSCAT.CHECKS.CONSTNAME
WITH UR 
