-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2025, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

SELECT
  AUTHID AS USERNAME,
  BINDADDAUTH,
  CONNECTAUTH,
  CREATETABAUTH,
  DBADMAUTH,
  EXTERNALROUTINEAUTH,
  IMPLSCHEMAAUTH,
  LOADAUTH,
  NOFENCEAUTH,
  QUIESCECONNECTAUTH,
  SECURITYADMAUTH,
  SQLADMAUTH,
  WLMADMAUTH,
  EXPLAINAUTH,
  DATAACCESSAUTH,
  ACCESSCTRLAUTH,
  CREATESECUREAUTH
FROM
  SYSIBMADM.AUTHORIZATIONIDS A
  LEFT JOIN SYSCAT.DBAUTH D
    ON D.GRANTEE = A.AUTHID
WHERE
  AUTHIDTYPE = 'U'
WITH UR
