SELECT
  NULLIF(1, 1) AS SYNONYM_CATALOG,
  LTRIM(RTRIM(TABSCHEMA)) AS SYNONYM_SCHEMA,
  LTRIM(RTRIM(TABNAME)) AS SYNONYM_NAME,
  NULLIF(1, 1) AS REFERENCED_OBJECT_CATALOG,
  LTRIM(RTRIM(BASE_TABSCHEMA)) AS REFERENCED_OBJECT_SCHEMA,
  LTRIM(RTRIM(BASE_TABNAME)) AS REFERENCED_OBJECT_NAME
FROM
  SYSCAT.TABLES
WHERE
  TYPE = 'A'
WITH UR
