SELECT
  NULLIF(1, 1) AS CONSTRAINT_CATALOG,
  STRIP(TABLE_CONSTRAINTS.TABSCHEMA) AS CONSTRAINT_SCHEMA,
  STRIP(TABLE_CONSTRAINTS.TABNAME) AS TABLE_NAME,
  STRIP(TABLE_CONSTRAINTS.CONSTNAME) AS CONSTRAINT_NAME,
  TABLE_CONSTRAINTS.REMARKS AS REMARKS,
  NULL AS CONSTRAINT_DEFINITION
FROM
  SYSCAT.TABCONST AS TABLE_CONSTRAINTS
ORDER BY
  TABLE_CONSTRAINTS.TABSCHEMA,
  TABLE_CONSTRAINTS.TABNAME,
  TABLE_CONSTRAINTS.CONSTNAME
WITH UR  
