SELECT
  NULLIF(1, 1)
    AS INDEX_CATALOG,
  STRIP(SYSCAT.INDEXES.INDSCHEMA)
    AS INDEX_SCHEMA,
  STRIP(SYSCAT.INDEXES.TABNAME)
    AS TABLE_NAME,  
  STRIP(SYSCAT.INDEXES.INDNAME)
    AS INDEX_NAME, 
  SYSCAT.INDEXES.REMARKS
    AS REMARKS,
  NULL AS INDEX_DEFINITION,
  STRIP(SYSCAT.INDEXES.INDEXTYPE)
    AS INDEX_TYPE,
  SYSCAT.INDEXES.CREATE_TIME,
  SYSCAT.INDEXES.STATS_TIME
FROM
  SYSCAT.INDEXES
WITH UR
