version: '3.7'

services:

  oracle:
    # https://hub.docker.com/r/gvenzl/oracle-xe
    image: gvenzl/oracle-xe:11-slim
    container_name: oracle
    ports:
      - target: 1521
        published: 1521
        protocol: tcp
        mode: host
    environment:
      ORACLE_PASSWORD: test
