var forEach = Array.prototype.forEach;

print('-- generated by ' + crawl_info.schemacrawlerVersion())
print('-- generated on ' + crawl_info.timestamp())

forEach.call(catalog.getTables(), function(table)
{
  print('');
  print(table.getFullName());
  forEach.call(table.getColumns(), function(column)
  {
    print("  " + column.getName());
  });
});
