print(f'-- generated by {crawl_info.schemacrawlerVersion()}')
print(f'-- generated on {crawl_info.timestamp()}')

for table in catalog.getTables():
  print('')
  print(table.getFullName())
  for column in table.getColumns():
    print("  " + column.getName())
