-- See SchemaCrawer issue #216

CREATE TABLE A(
  ID INTEGER PRIMARY KEY,
  DATAP TEXT COLLATE NOCASE NOT NULL UNIQUE,
  DATAQ TEXT NOT NULL
);

CREATE TABLE B(
  ID INTEGER PRIMARY KEY,
  A_ID INTEGER NOT NULL REFERENCES A,
  DATAX TEXT COLLATE NOCASE NOT NULL,
  DATAY NUMERIC
);
