CREATE TABLE DATA(OWNERID TEXT);
CREATE VIEW OBJECT_OWNER AS SELECT * FROM DATA;
INSERT INTO DATA VALUES('1');
ALTER TABLE DATA RENAME TO _DATA;
CREATE TABLE DATA(OWNERID TEXT);
INSERT INTO DATA VALUES('2');
