SELECT
  DB_NAME() AS SYNONYM_CATALOG,
  SCHEMA_NAME(SCHEMA_ID) AS SYNONYM_SCHEMA, 
  NAME AS SYNONYM_NAME, 
  PARSENAME(BASE_OBJECT_NAME, 4) AS REFERENCED_OBJECT_SERVER,
  PARSENAME(BASE_OBJECT_NAME, 3) AS REFERENCED_OBJECT_CATALOG,
  PARSENAME(BASE_OBJECT_NAME, 2) AS REFERENCED_OBJECT_SCHEMA,
  PARSENAME(BASE_OBJECT_NAME, 1) AS REFERENCED_OBJECT_NAME
FROM 
  SYS.SYNONYMS
