SELECT
  FK.CONSTRAINT_NAME AS FK_NAME,
  PK.TABLE_CATALOG AS FKTABLE_CAT,
  FK.TABLE_SCHEMA AS FKTABLE_SCHEM,
  FK.TABLE_NAME AS FKTABLE_NAME,
  FK.COLUMN_NAME AS FKCOLUMN_NAME,
  PK.CONSTRAINT_NAME AS PK_NAME,
  FK.ORDINAL_POSITION AS KEY_SEQ,
  PK.TABLE_CATALOG AS PKTABLE_CAT,
  PK.TABLE_SCHEMA AS PKTABLE_SCHEM,
  PK.TABLE_NAME AS PKTABLE_NAME,
  PK.COLUMN_NAME AS PKCOLUMN_NAME,
  CASE RC.UPDATE_RULE
    WHEN 'CASCADE' THEN 0
  WHEN 'SET NULL' THEN 2
  WHEN 'SET DEFAULT' THEN 4
  ELSE 3 -- no action
  END AS UPDATE_RULE,
  CASE RC.DELETE_RULE
    WHEN 'CASCADE' THEN 0
  WHEN 'SET NULL' THEN 2
  WHEN 'SET DEFAULT' THEN 4
  ELSE 3 -- no action
  END AS DELETE_RULE,
  7 AS DEFERRABILITY -- not deferrable
FROM
  INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS RC
  INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS FK
    ON FK.CONSTRAINT_CATALOG = RC.CONSTRAINT_CATALOG
    AND FK.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA
    AND FK.CONSTRAINT_NAME = RC.CONSTRAINT_NAME
  INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS PK
    ON PK.CONSTRAINT_CATALOG = RC.UNIQUE_CONSTRAINT_CATALOG
    AND PK.CONSTRAINT_SCHEMA = RC.UNIQUE_CONSTRAINT_SCHEMA
    AND PK.CONSTRAINT_NAME = RC.UNIQUE_CONSTRAINT_NAME
    AND PK.ORDINAL_POSITION = FK.ORDINAL_POSITION
