SELECT
  PRIMARY_KEYS.TABLE_CATALOG AS TABLE_CAT,
  PRIMARY_KEYS.TABLE_SCHEMA AS TABLE_SCHEM,
  PRIMARY_KEYS.TABLE_NAME,
  PRIMARY_KEYS.CONSTRAINT_NAME AS PK_NAME,
  PRIMARY_KEY_COLUMNS.COLUMN_NAME,
  PRIMARY_KEY_COLUMNS.ORDINAL_POSITION AS KEY_SEQ
FROM
  INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS PRIMARY_KEYS
  INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS PRIMARY_KEY_COLUMNS
    ON PRIMARY_KEYS.CONSTRAINT_TYPE = 'PRIMARY KEY'
      AND PRIMARY_KEYS.CONSTRAINT_NAME = PRIMARY_KEY_COLUMNS.CONSTRAINT_NAME
ORDER BY
  TABLE_CAT,
  TABLE_SCHEM,
  TABLE_NAME,
  PK_NAME,
  KEY_SEQ
