SELECT
  SEQUENCE_CATALOG,
  SEQUENCE_SCHEMA,
  SEQUENCE_NAME,
  DATA_TYPE,
  NUMERIC_PRECISION,
  NUMERIC_PRECISION_RADIX,
  NUMERIC_SCALE,
  CAST(START_VALUE AS BIGINT) AS START_VALUE,
  CAST(MINIMUM_VALUE AS BIGINT) AS MINIMUM_VALUE,
  CAST(MAXIMUM_VALUE AS BIGINT) AS MAXIMUM_VALUE,
  CAST(INCREMENT AS BIGINT) AS INCREMENT,
  CYCLE_OPTION,
  DECLARED_DATA_TYPE,
  DECLARED_NUMERIC_PRECISION,
  DECLARED_NUMERIC_SCALE
FROM
  INFORMATION_SCHEMA.SEQUENCES
ORDER BY
  SEQUENCE_CATALOG,
  SEQUENCE_SCHEMA,
  SEQUENCE_NAME
