SELECT
  TABLE_CATALOG,
  TABLE_SCHEMA,
  TABLE_NAME,
  CHECK_OPTION,
  IS_UPDATABLE,
  OBJECT_DEFINITION(OBJECT_ID(TABLE_CATALOG + '.' + TABLE_SCHEMA + '.' + TABLE_NAME))
    AS VIEW_DEFINITION
FROM
  INFORMATION_SCHEMA.VIEWS
