CREATE DATABASE DATABASE_A;
USE DATABASE_A;

CREATE TABLE DBO.A_DBO_TABLE1
(
  Id INT PRIMARY KEY NOT NULL,
  Name VARCHAR(40) NOT NULL
);

CREATE TABLE DBO.A_DBO_TABLE2
(
  Id INT PRIMARY KEY NOT NULL,
  Name VARCHAR(40) NOT NULL,
  FK_COL_TO_DBO INT NOT NULL,
  CONSTRAINT FK_DBO_TO_DBO FOREIGN KEY (FK_COL_TO_DBO) REFERENCES A_DBO_TABLE1 (Id)
);

-- ---------------------------

CREATE DATABASE DATABASE_B;
USE DATABASE_B;

CREATE TABLE DBO.B_DBO_TABLE1
(
  Id INT PRIMARY KEY NOT NULL,
  Name VARCHAR(40) NOT NULL
);

CREATE TABLE DBO.B_DBO_TABLE2
(
  Id INT PRIMARY KEY NOT NULL,
  Name VARCHAR(40) NOT NULL,
  FK_COL_TO_DBO INT NOT NULL,
  CONSTRAINT FK_DBO_TO_DBO FOREIGN KEY (FK_COL_TO_DBO) REFERENCES B_DBO_TABLE1 (Id)
);

-- ---------------------------

USE DATABASE master;
