SELECT
  PROCEDURE_CAT
  AS ROUTINE_CATALOG,
  PROCEDURE_SCHEM
  AS ROUTINE_SCHEMA,
  PROCEDURE_NAME
  AS ROUTINE_NAME,
'EXTERNAL' AS ROUTINE_BODY,
  SPECIFIC_NAME
  AS ROUTINE_DEFINITION
FROM
  INFORMATION_SCHEMA.SYSTEM_PROCEDURES