CREATE TABLE TABLE1_PK
(
  ENTITY_ID INTEGER NOT NULL,
  COL12 CHAR(25),
  COL13 VARCHAR(25),
  COL14 NUMERIC NOT NULL,
  COL15 VARCHAR(25),
  PRIMARY KEY (ENTITY_ID)
);

CREATE TABLE TABLE2_PK
(
  ENTITY_ID INTEGER NOT NULL,
  COL22 CHAR(25),
  COL23 VARCHAR(25),
  COL24 NUMERIC NOT NULL,
  COL25 VARCHAR(25),
  PRIMARY KEY (ENTITY_ID)
);

CREATE TABLE TABLE3_FK
(
  ENTITY3_ID INTEGER NOT NULL,
  ENTITY_ID INTEGER NOT NULL,
  COL32 CHAR(25),
  COL33 VARCHAR(25),
  COL34 NUMERIC NOT NULL,
  COL35 VARCHAR(25),
  PRIMARY KEY (ENTITY3_ID),
  FOREIGN KEY (ENTITY_ID) REFERENCES TABLE1_PK(ENTITY_ID)
);

CREATE TABLE TABLE4_UNIQUE
(
  ENTITY_ID INTEGER NOT NULL,
  COL12 CHAR(25),
  COL13 VARCHAR(25),
  COL14 NUMERIC NOT NULL,
  COL15 VARCHAR(25),
  UNIQUE (ENTITY_ID)
);

CREATE TABLE TABLE5_FK
(
  ENTITY5_ID INTEGER NOT NULL,
  ENTITY_ID INTEGER NOT NULL,
  COL32 CHAR(25),
  COL33 VARCHAR(25),
  COL34 NUMERIC NOT NULL,
  COL35 VARCHAR(25),
  PRIMARY KEY (ENTITY5_ID),
  FOREIGN KEY (ENTITY_ID) REFERENCES TABLE4_UNIQUE(ENTITY_ID)
);
