CREATE TABLE TABLE1_SECTION1_BOOKS
(
  BOOK INTEGER NOT NULL,
  COL12 CHAR(25),
  COL13 VARCHAR(25),
  COL14 NUMERIC NOT NULL,
  COL15 VARCHAR(25),
  PRIMARY KEY (BOOK)
);

CREATE TABLE BOOK
(
  BOOK_ID INTEGER NOT NULL,
  COL22 CHAR(25),
  COL23 VARCHAR(25),
  COL24 NUMERIC NOT NULL,
  COL25 VARCHAR(25),
  PRIMARY KEY (BOOK_ID)
);

CREATE TABLE TABLE3_WEAK
(
  WEAK_ID INTEGER NOT NULL,
  BOOK INTEGER NOT NULL,
  COL32 CHAR(25),
  COL33 VARCHAR(25),
  COL34 NUMERIC NOT NULL,
  COL35 VARCHAR(25),
  PRIMARY KEY (WEAK_ID)
);

CREATE TABLE TABLE4_WEAK
(
  WEAK_ID INTEGER NOT NULL,
  BOOKID INTEGER NOT NULL,
  COL42 CHAR(25),
  COL43 VARCHAR(25),
  COL44 NUMERIC NOT NULL,
  COL45 VARCHAR(25),
  PRIMARY KEY (WEAK_ID)
);

CREATE TABLE TABLE5_WEAK
(
  WEAK_ID INTEGER NOT NULL,
  BOOK_ID INTEGER NOT NULL,
  COL52 CHAR(25),
  COL53 VARCHAR(25),
  COL54 NUMERIC NOT NULL,
  COL55 VARCHAR(25),
  PRIMARY KEY (WEAK_ID)
);

CREATE TABLE TABLE6_WEAK
(
  WEAK_ID INTEGER NOT NULL,
  AUTHOR_ID INTEGER NOT NULL,
  COL62 CHAR(25),
  COL63 VARCHAR(25),
  COL64 NUMERIC NOT NULL,
  COL65 VARCHAR(25),
  PRIMARY KEY (WEAK_ID)
);
