SELECT
  CURRENT_DATABASE()::INFORMATION_SCHEMA.SQL_IDENTIFIER AS CONSTRAINT_CATALOG,
  CONSTRAINTS.CONSTRAINT_SCHEMA,
  CONSTRAINTS.CONSTRAINT_NAME,
  CONSTRAINTS.CHECK_CLAUSE
FROM
  INFORMATION_SCHEMA.CHECK_CONSTRAINTS AS CONSTRAINTS
