-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2025, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

SELECT
  CURRENT_DATABASE()::INFORMATION_SCHEMA.SQL_IDENTIFIER AS CONSTRAINT_CATALOG,
  CONSTRAINTS.CONSTRAINT_SCHEMA,
  CONSTRAINTS.CONSTRAINT_NAME,
  CONSTRAINTS.CHECK_CLAUSE
FROM
  INFORMATION_SCHEMA.CHECK_CONSTRAINTS AS CONSTRAINTS
