SELECT
  NULL AS INDEX_CATALOG,
  SCHEMANAME AS INDEX_SCHEMA,
  INDEXNAME AS INDEX_NAME,
  TABLENAME AS TABLE_NAME,
  INDEXDEF AS INDEX_DEFINITION
FROM
  PG_INDEXES
ORDER BY
  SCHEMANAME,
  TABLENAME,
  INDEXNAME
