SELECT
  NULL AS INDEX_CATALOG,
  SCHEMANAME AS INDEX_SCHEMA,
  INDEXNAME AS INDEX_NAME,
  TABLENAME AS TABLE_NAME,
  CASE WHEN INDEXDEF LIKE '%UNIQUE%' THEN 'YES' ELSE 'NO' END AS IS_UNIQUE,
  INDEXDEF AS INDEX_DEFINITION
FROM
  PG_INDEXES
ORDER BY
  SCHEMANAME,
  TABLENAME,
  INDEXNAME
