-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2026, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

SELECT
  CURRENT_DATABASE()::INFORMATION_SCHEMA.SQL_IDENTIFIER AS ROUTINE_CATALOG,
  ROUTINE_SCHEMA,
  ROUTINE_NAME,
  SPECIFIC_NAME,
  ROUTINE_BODY,
  ROUTINE_DEFINITION
FROM
  INFORMATION_SCHEMA.ROUTINES
ORDER BY
  ROUTINE_CATALOG,
  ROUTINE_SCHEMA,
  ROUTINE_NAME
  