SELECT
  NULL AS SEQUENCE_CATALOG,
  SEQUENCE_SCHEMA,
  SEQUENCE_NAME,
  INCREMENT,
  MINIMUM_VALUE,
  MAXIMUM_VALUE,
  CYCLE_OPTION
FROM
  INFORMATION_SCHEMA.SEQUENCES
ORDER BY
  SEQUENCE_CATALOG,
  SEQUENCE_SCHEMA,
  SEQUENCE_NAME
