-- APPEND A SQL TERMINATOR TO EACH DDL STATEMENT
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', TRUE)};
-- SUPRESS ALL NON-REFERENTIAL TABLE CONSTRAINTS
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'CONSTRAINTS', FALSE)};
-- SUPRESS ALL REFERENTIAL TABLE CONSTRAINTS
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'REF_CONSTRAINTS', FALSE)};
-- EMIT THE BYTE KEYWORD AS PART OF THE SIZE SPECIFICATION OF CHAR AND VARCHAR2 COLUMNS THAT USE BYTE SEMANTICS
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SIZE_BYTE_KEYWORD', TRUE)};
