-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2026, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

-- APPEND A SQL TERMINATOR TO EACH DDL STATEMENT
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', TRUE)};
-- EMIT THE BYTE KEYWORD AS PART OF THE SIZE SPECIFICATION OF CHAR AND VARCHAR2 COLUMNS THAT USE BYTE SEMANTICS
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SIZE_BYTE_KEYWORD', TRUE)};
-- SPECIFY THAT STORAGE CLAUSES ARE NOT TO BE RETURNED IN THE SQL DDL
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SPECIFICATION', FALSE)};
-- SUPPRESS THE SCHEMA-NAME
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'EMIT_SCHEMA', FALSE)};
-- SUPRESS SEGMENT ATTRIBUTES (PHYSICAL ATTRIBUTES, STORAGE ATTRIBUTES, TABLESPACE, LOGGING)
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', FALSE)};
-- SUPRESS PARTITIONING CLAUSES
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'PARTITIONING', FALSE)};
-- SUPRESS STORAGE CLAUSE (IGNORED IF SEGMENT_ATTRIBUTES IS FALSE)
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', FALSE)};
-- SUPRESS TABLESPACE (IGNORED IF SEGMENT_ATTRIBUTES IS FALSE) 
{call DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', FALSE)};
