-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2025, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

SELECT
  SYNONYM_CATALOG,
  SYNONYM_SCHEMA,
  SYNONYM_NAME,
  OBJECT_CATALOG AS REFERENCED_OBJECT_CATALOG,
  OBJECT_SCHEMA AS REFERENCED_OBJECT_SCHEMA,
  OBJECT_NAME AS REFERENCED_OBJECT_NAME,
  OBJECT_TYPE AS REFERENCED_OBJECT_TYPE
FROM
  INFORMATION_SCHEMA.SYSTEM_SYNONYMS
