SELECT
  SYNONYM_CATALOG,
  SYNONYM_SCHEMA,
  SYNONYM_NAME,
  OBJECT_CATALOG AS REFERENCED_OBJECT_CATALOG,
  OBJECT_SCHEMA AS REFERENCED_OBJECT_SCHEMA,
  OBJECT_NAME AS REFERENCED_OBJECT_NAME,
  OBJECT_TYPE AS REFERENCED_OBJECT_TYPE
FROM
  INFORMATION_SCHEMA.SYSTEM_SYNONYMS
