-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2025, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

SELECT
  TABLE_CATALOG AS TABLE_CAT,
  TABLE_SCHEMA AS TABLE_SCHEM,
  TABLE_NAME,
  COLUMN_NAME,
  GRANTOR,
  GRANTEE,
  PRIVILEGE_TYPE AS PRIVILEGE,
  IS_GRANTABLE
FROM
  INFORMATION_SCHEMA.COLUMN_PRIVILEGES
ORDER BY
  TABLE_CATALOG,
  TABLE_SCHEMA,
  TABLE_NAME,
  COLUMN_NAME,
  PRIVILEGE_TYPE,  
  GRANTOR,
  GRANTEE
