SELECT
  TABLE_CATALOG AS TABLE_CAT,
  TABLE_SCHEMA AS TABLE_SCHEM,
  TABLE_NAME,
  COLUMN_NAME,
  GRANTOR,
  GRANTEE,
  PRIVILEGE_TYPE AS PRIVILEGE,
  IS_GRANTABLE
FROM
  INFORMATION_SCHEMA.COLUMN_PRIVILEGES
ORDER BY
  TABLE_CATALOG,
  TABLE_SCHEMA,
  TABLE_NAME,
  COLUMN_NAME,
  PRIVILEGE_TYPE,  
  GRANTOR,
  GRANTEE
