-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2026, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

-- Oracle syntax
CREATE USER BOOKS IDENTIFIED BY BOOKS;
GRANT CONNECT TO BOOKS;
GRANT UNLIMITED TABLESPACE TO BOOKS;
GRANT CREATE MATERIALIZED VIEW TO BOOKS;
GRANT QUERY REWRITE TO BOOKS;
GRANT CREATE ANY TABLE TO BOOKS;
ALTER SESSION SET CURRENT_SCHEMA = BOOKS;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
