-- Domains
CREATE DOMAIN VALID_STRING 
AS VARCHAR(20) 
  DEFAULT 'NO VALUE' 
  CHECK (VALUE IS NOT NULL AND CHARACTER_LENGTH(VALUE) > 2);

-- Table using domains
CREATE TABLE CustomerData
(
  Id INTEGER NOT NULL,  
  Data VALID_STRING,
  CONSTRAINT PK_CustomerData PRIMARY KEY (Id)
)
;
