-- Global temporary table
-- Apache Derby Syntax
DECLARE GLOBAL TEMPORARY TABLE TEMP_AUTHOR_LIST
(
  Id INTEGER NOT NULL,
  FirstName VARCHAR(20) NOT NULL,
  LastName VARCHAR(20) NOT NULL
)
NOT LOGGED
;
