-- Table with auto-incremented column, 
-- associated with an internal sequence generator 
-- Firebird syntax
CREATE TABLE Publishers
(
  ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Publisher VARCHAR(255)
)
;
