-- Local temporary table
CREATE TEMPORARY TABLE TEMP_AUTHOR_LIST
(
  Id INTEGER NOT NULL,
  FirstName VARCHAR(20) NOT NULL,
  LastName VARCHAR(20) NOT NULL,
  CONSTRAINT PK_Tmp_Authors PRIMARY KEY (Id)
)
;
