-- Table with identity column, generated
-- with an unnamed primary key
-- Oracle 12c syntax
CREATE TABLE Publishers
(
  Id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  Publisher VARCHAR(255),
  CONSTRAINT PRIMARY KEY (Id)
)
;
