-- Generated columns
-- IBM DB2 syntax
CREATE TABLE X_EMPLOYEES( 
  EMPLOYEEID INTEGER NOT NULL,
  EMPLOYEE_NAME VARCHAR(30), 
  START_DATE DATE, 
  END_DATE DATE,
  ANNUAL_SALARY INTEGER,
  HOURLY_RATE GENERATED ALWAYS AS (ANNUAL_SALARY/2080)
); 
