-- Generated columns
-- MySQL 5.7.6 syntax
CREATE TABLE X_EMPLOYEES
( 
  EMPLOYEEID INTEGER NOT NULL,
  EMPLOYEE_NAME VARCHAR(30), 
  START_DATE DATE, 
  END_DATE DATE, 
  ANNUAL_SALARY INTEGER,
  HOURLY_RATE DOUBLE AS (ANNUAL_SALARY/2080),
  ACTIVE CHAR(1) AS (CASE WHEN END_DATE IS NULL THEN 'Y' ELSE 'N' END)
); 
