-- IBM DB2: Generated (but not hidden) columns
CREATE TABLE X_EMPLOYEES( 
  EMPLOYEEID INTEGER NOT NULL,
  EMPLOYEE_NAME VARCHAR(30), 
  START_DATE DATE, 
  END_DATE DATE,
  ANNUAL_SALARY INTEGER,
  HOURLY_RATE GENERATED ALWAYS AS (ANNUAL_SALARY/2080)
); 

-- IBM DB2: Hidden columns
CREATE TABLE X_CUSTOMERS
(
  CUSTOMERID INTEGER NOT NULL,
  CUSTOMER_NAME VARCHAR(80),
  SOCIAL_SECURITY_NUMBER CHAR(9) IMPLICITLY HIDDEN
);
