-- Table with auto-incremented column, using sequences
-- with an unnamed primary key
CREATE TABLE Publishers
(
  Id INTEGER GENERATED BY DEFAULT AS SEQUENCE Publisher_Id_Seq PRIMARY KEY,
  Publisher VARCHAR(255)
)
;