-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2026, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

-- Table with auto-incremented column, using sequences
-- with an unnamed primary key
CREATE TABLE Publishers
(
  Id INTEGER GENERATED BY DEFAULT AS SEQUENCE Publisher_Id_Seq PRIMARY KEY,
  Publisher VARCHAR(255)
)
;