-- SchemaCrawler
-- http://www.schemacrawler.com
-- Copyright (c) 2000-2025, Sualeh Fatehi <sualeh@hotmail.com>.
-- All rights reserved.
-- SPDX-License-Identifier: EPL-2.0

-- Table with auto-incremented column, 
-- associated with an internal sequence generator 
-- Firebird syntax
CREATE TABLE Publishers
(
  ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Publisher VARCHAR(255)
)
;
