-- Generated columns
-- Oracle syntax
CREATE TABLE X_EMPLOYEES( 
  EMPLOYEEID INTEGER NOT NULL,
  EMPLOYEE_NAME VARCHAR2(30), 
  START_DATE DATE, 
  END_DATE DATE, 
  ANNUAL_SALARY INTEGER,
  HOURLY_RATE GENERATED ALWAYS AS (ANNUAL_SALARY/2080), 
  ACTIVE AS (CASE WHEN END_DATE IS NULL THEN 'Y' ELSE 'N' END)
); 