-- Create Oracle user with just select catalog role
CREATE USER CATUSER IDENTIFIED BY CATUSER;
GRANT CONNECT TO CATUSER;
GRANT SELECT_CATALOG_ROLE TO CATUSER;


-- Create Oracle user with just SELECT grant
CREATE USER SELUSER IDENTIFIED BY SELUSER;
GRANT CONNECT TO SELUSER;
GRANT CREATE SESSION TO SELUSER;
GRANT SELECT ON BOOKS.AUTHORS TO SELUSER;


-- Create Oracle user with no access
CREATE USER NOTUSER IDENTIFIED BY NOTUSER;
GRANT CONNECT TO NOTUSER;
