INSERT INTO `Global Counts` (`Global Count`,`UPDATE`) VALUES (1,'Abbot');
INSERT INTO `Global Counts` (`Global Count`,`UPDATE`) VALUES (2,'Alexis');
INSERT INTO `Global Counts` (`Global Count`,`UPDATE`) VALUES (3,'Jasmine');
INSERT INTO `Global Counts` (`Global Count`,`UPDATE`) VALUES (4,NULL);
INSERT INTO `Global Counts` (`Global Count`,`UPDATE`) VALUES (5,'Teagan');
INSERT INTO `Global Counts` (`Global Count`,`UPDATE`) VALUES (6,'Stella');
INSERT INTO `Global Counts` (`Global Count`,`UPDATE`) VALUES (7,'Alden');
INSERT INTO `Global Counts` (`Global Count`,`UPDATE`) VALUES (8,'Daniel');
INSERT INTO `Global Counts` (`Global Count`,`UPDATE`) VALUES (9,NULL);
INSERT INTO `Global Counts` (`Global Count`,`UPDATE`) VALUES (10,'Yetta');

INSERT INTO Coupons (Id,Data) VALUES (1,'sollicitudin commodo ipsum. Suspendisse non');
INSERT INTO Coupons (Id,Data) VALUES (2,'Nunc ut erat. Sed nunc est, mollis non, cursus non,');
INSERT INTO Coupons (Id,Data) VALUES (3,'turpis non enim. Mauris quis');
INSERT INTO Coupons (Id,Data) VALUES (4,'lectus ante dictum mi,');
INSERT INTO Coupons (Id,Data) VALUES (5,NULL);
INSERT INTO Coupons (Id,Data) VALUES (6,'vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum.');
INSERT INTO Coupons (Id,Data) VALUES (7,'quis, pede. Praesent eu dui. Cum sociis natoque penatibus et');
INSERT INTO Coupons (Id,Data) VALUES (8,NULL);
INSERT INTO Coupons (Id,Data) VALUES (9,'auctor quis, tristique ac, eleifend vitae, erat. Vivamus');
INSERT INTO Coupons (Id,Data) VALUES (10,'amet risus. Donec egestas. Aliquam nec enim.');
