CREATE SCHEMA "SCHEMA1" AUTHORIZATION DBA;
SET SCHEMA "SCHEMA1";

CREATE TABLE TableA
(
  Id INTEGER NOT NULL,
  A VARCHAR(20) NOT NULL,
  CONSTRAINT PK_TableA PRIMARY KEY (Id)
)
;

CREATE TABLE TableB
(
  Id INTEGER NOT NULL,
  B VARCHAR(20) NOT NULL,
  CONSTRAINT FK_TableA FOREIGN KEY (Id) REFERENCES TableA (Id)
)
;

CREATE SCHEMA "SCHEMA2" AUTHORIZATION DBA;
SET SCHEMA "SCHEMA2";

CREATE TABLE TableA
(
  Id INTEGER NOT NULL,
  A VARCHAR(20) NOT NULL,
  CONSTRAINT PK_TableA PRIMARY KEY (Id)
)
;

CREATE TABLE TableB
(
  Id INTEGER NOT NULL,
  B VARCHAR(20) NOT NULL,
  CONSTRAINT FK_TableA FOREIGN KEY (Id) REFERENCES TableA (Id)
)
;

