CREATE SCHEMA "SCHEMA1" AUTHORIZATION DBA;

CREATE TABLE SCHEMA1.TableA
(
  Id INTEGER NOT NULL,
  A VARCHAR(20) NOT NULL,
  CONSTRAINT PK_TableA PRIMARY KEY (Id)
)
;

CREATE TABLE SCHEMA1.TableB
(
  Id INTEGER NOT NULL,
  B VARCHAR(20) NOT NULL,
  CONSTRAINT FK_TableA FOREIGN KEY (Id) REFERENCES TableA (Id)
)
;

CREATE SCHEMA "SCHEMA2" AUTHORIZATION DBA;

CREATE TABLE SCHEMA2.TableA
(
  Id INTEGER NOT NULL,
  A VARCHAR(20) NOT NULL,
  CONSTRAINT PK_TableA PRIMARY KEY (Id)
)
;

CREATE TABLE SCHEMA2.TableB
(
  Id INTEGER NOT NULL,
  B VARCHAR(20) NOT NULL,
  CONSTRAINT FK_TableA FOREIGN KEY (Id) REFERENCES TableA (Id)
)
;

