CREATE TABLE CITIES (
  CODE INT PRIMARY KEY,
  NAME VARCHAR(20),
  STATE_CODE VARCHAR(20)
);

CREATE TABLE COUNTRIES (
  CODE INT PRIMARY KEY,
  NAME VARCHAR(20),
  CONTINENT_CODE VARCHAR(20)
);

CREATE TABLE PERSONS (
  ID INT PRIMARY KEY,
  NAME VARCHAR(20),
  CITY_CODE INT,
  COUNTRY_CODE INT,
  SPOUSE INT,
  MANAGER INT,
  CUSTOMER INT,
  FOREIGN KEY (SPOUSE) REFERENCES PERSONS(ID),
  FOREIGN KEY (MANAGER) REFERENCES PERSONS(ID),
  FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRIES(CODE),  
  FOREIGN KEY (CITY_CODE) REFERENCES CITIES(CODE)
);

CREATE TABLE EMPLOYEES (
  ID INT PRIMARY KEY,
  PERSON INT,
  FOREIGN KEY (PERSON) REFERENCES PERSONS(ID)
);


CREATE TABLE CUSTOMERS (
  ID INT PRIMARY KEY,
  PERSON INT,
  FOREIGN KEY (PERSON) REFERENCES PERSONS(ID)
);

ALTER TABLE PERSONS ADD FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMERS(ID);
