# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

import re

print("@startuml")
print("""
!theme plain
hide empty methods

!procedure $schema($name, $slug)
package "$name" as $slug <<Rectangle>>
!endprocedure

!procedure $table($name, $slug)
entity "<b>$name</b>" as $slug << (T, Orange) table >>
!endprocedure

!procedure $view($name, $slug)
entity "<b>$name</b>" as $slug << (V, Aquamarine) view >>
!endprocedure

!procedure $pk($name)
<color:#GoldenRod><&key></color> <b>$name</b>
!endprocedure

!procedure $fk($name)
<color:#Silver><&key></color> $name
!endprocedure

!procedure $column($name)
{field} <color:#Transparent><&media-record></color> $name
!endprocedure

""")

print('title "' + title + '"')
print('')
print('legend bottom right')
print('generated by ' + support.schemacrawlerVersion())
print('generated on ' + support.crawlTimestamp())
print('end legend')
print('')
print('')

# Tables
for schema in catalog.getSchemas():
    if not catalog.getTables(schema):
        continue
    print('$schema("' + re.sub(r'\"', '', schema.getFullName()) + '", "' + support.slug(schema) + '") {')
    print('')
    for table in catalog.getTables(schema):
        if not support.isView(table):
            print('$table', end='')
        else:
            print('$view', end='')
        print('("' + re.sub(r'\"', '', table.getName()) + '", "' + support.slug(table) + '") {')
        for column in table.getColumns():
            if column.isPartOfPrimaryKey():
                print('  $pk', end='')
            elif column.isPartOfForeignKey():
                print('  $fk', end='')
            else:
                print('  $column', end='')
            print('("' + column.getName() + '"): ' + support.columnTypeName(column), end='')
            print(' ', end='')
            if not column.isNullable():
                print('NOT NULL', end='')
            print('')
        print('}')
        print('')
        if table.hasRemarks():
            print('note left of ' + support.slug(table) + ' #LemonChiffon')
            print(table.getRemarks())
            print('end note')
            print('')
        for column in table.getColumns():
            if column.hasRemarks():
                print('note right of ' + support.slug(table) + '::' + column.getName() + ' #LightCyan')
                print(column.getRemarks())
                print('end note')
                print('')
        print('')
        print('')
    print('')
    print('}')
    print('')
    print('')

# Foreign keys
for table in catalog.getTables():
    for fk in table.getExportedForeignKeys():
        pkTable = fk.getPrimaryKeyTable()
        fkTable = fk.getForeignKeyTable()
        for columnReference in fk.getColumnReferences():
            pkColumn = columnReference.getPrimaryKeyColumn()
            fkColumn = columnReference.getForeignKeyColumn()
            print(pkTable.getSchema().key().slug() + '.' +
                  support.slug(pkTable) + '::' +
                  re.sub(r'\"', '', pkColumn.getName()) +
                  '  ||--o{ ' +
                  fkTable.getSchema().key().slug() + '.' +
                  support.slug(fkTable) + '::' +
                  re.sub(r'\"', '', fkColumn.getName()), end='')
            if support.hasName(fk):
                print(' : ' + fk.getName(), end='')
            print('')
print('')

print("@enduml")
