import schemacrawler.schema.Catalog
import schemacrawler.schema.Column
import schemacrawler.schema.ForeignKey
import schemacrawler.schema.PrimaryKey
import schemacrawler.schema.Schema
import schemacrawler.schema.Table
import schemacrawler.schema.View

String title
Catalog catalog

print("@startuml")
print('''
!theme plain
hide empty methods

!procedure $schema($name, $slug)
package "$name" as $slug <<Rectangle>>
!endprocedure

!procedure $table($name, $slug)
entity "<b>$name</b>" as $slug << (T, Orange) table >>
!endprocedure

!procedure $view($name, $slug)
entity "<b>$name</b>" as $slug << (V, Aquamarine) view >>
!endprocedure

!procedure $pk($name)
<color:#GoldenRod><&key></color> <b>$name</b>
!endprocedure

!procedure $fk($name)
<color:#Silver><&key></color> $name
!endprocedure

!procedure $column($name)
{field} <color:#White><&media-record></color> $name
!endprocedure

''')

print('title "' + title + '"')
print('')
print('legend bottom right')
print('generated by ' + catalog.crawlInfo.schemaCrawlerVersion.toString())
print('generated on ' + catalog.crawlInfo.crawlTimestamp)
print('end legend')
print('')
print('')

catalog.schemas.each { schema ->
  if (catalog.getTables(schema)) {
    println("\$schema(\"${schema.fullName.replaceAll('\"', '')}\", \"${schema.key().slug()}\") {")
    println()

    catalog.getTables(schema).each { table ->

      if (!table.tableType.view) {
        print('$table')
      } else {
        print('$view')
      }
      println("(\"${table.name.replaceAll('\"', '')}\", \"${table.key().slug()}\") {")
table.columns.each {column->

}
    }

  }
}
