# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

print(f'# generated by {crawl_info.schemacrawlerVersion()}')
print(f'# generated on {crawl_info.timestamp()}')
print(f'# database: {crawl_info.databaseVersion()}')
print()

for schema in catalog.getSchemas():

	tables = catalog.getTables(schema)
	if not tables:
		continue

	print()
	print()

	for table in tables:

		if table.hasRemarks():
			print(f'# {support.remarks(table)}')
		print(f'"{table.getName()}" as {table.key().slug()}')
		print(f'# {table.getFullName()}')	
		print('------')

		for column in table.getColumns():
			col_name = f'"{column.getName()}"'
			col_type = f'"{column.getColumnDataType().getDatabaseSpecificTypeName()}{column.getWidth()}"'
			if column.hasDefaultValue():
				col_type = col_type + f'="{column.getDefaultValue()}"'
			modifiers = []
			if column.isPartOfPrimaryKey():
				modifiers.append('PK')
			elif column.isPartOfUniqueIndex():
				modifiers.append('UNIQUE')
			elif column.isPartOfIndex():
				modifiers.append('INDEX')
			if column.isNullable():
				modifiers.append('NULLABLE')
			if column.isAutoIncremented():
				modifiers.append('AUTOINCREMENT')
			if column.isPartOfForeignKey():
				ref_table_slug = column.getReferencedColumn().getParent().key().slug()
				ref_col_name = column.getReferencedColumn().getName()
				modifiers.append(f'FK >- {ref_table_slug}."{ref_col_name}"')
			if column.hasRemarks():
				modifiers.append(f'  # {support.remarks(column)}')								
			col_mods = ' '.join(modifiers)

			print(f'  {col_name} {col_type}', end='')
			if col_mods:
				print(f' {col_mods}')
			else:
				print()

		print()
