name: Compare Database Schema Outputs

on:
  workflow_dispatch:

jobs:
  diff-output:
    runs-on: ubuntu-latest

    steps:
    - id: setup-node
      uses: actions/setup-node@v5
      with:
        node-version: latest

    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v5

    - id: install-diff2html
      name: Install diff2html
      shell: bash
      run: |
        # Install diff2html-cli
        npm config set fund false
        npm --version
        diff --version
        npm install -g diff2html-cli
        diff2html --version

    - id: generate-diff
      name: Compare files and generate diff
      shell: sh
      run: |
        # Generate diff in HTML
        #
        mkdir --verbose diff-output/
        #
        ./.github/scripts/diff-output.sh \
          schemacrawler-oracle/src/test/resources/testOraclePortable.txt \
          schemacrawler-sqlserver/src/test/resources/testSQLServerPortable.txt \
          ./diff-output/compare-oracle-sqlserver.html \
          "Compare Oracle - SQL Server"
        #
        ./.github/scripts/diff-output.sh \
          schemacrawler-oracle/src/test/resources/testOraclePortable.txt \
          schemacrawler-mysql/src/test/resources/testMySQLPortable.txt \
          ./diff-output/compare-oracle-mysql.html \
          "Compare Oracle - MySQL"
        #
        ./.github/scripts/diff-output.sh \
          schemacrawler-oracle/src/test/resources/testOraclePortable.txt \
          schemacrawler-db2/src/test/resources/testDB2Portable.txt \
          ./diff-output/compare-oracle-db2.html \
          "Compare Oracle - IBM DB2"
        #
        ./.github/scripts/diff-output.sh \
          schemacrawler-oracle/src/test/resources/testOraclePortable.txt \
          schemacrawler-postgresql/src/test/resources/testPostgreSQLPortable.txt \
          ./diff-output/compare-oracle-postgresql.html \
          "Compare Oracle - PostgreSQL"
        #
        ./.github/scripts/diff-output.sh \
          schemacrawler-oracle/src/test/resources/testOraclePortable.txt \
          schemacrawler-sqlite/src/test/resources/testSqlitePortable.txt \
          ./diff-output/compare-oracle-sqlite.html \
          "Compare Oracle - SQLite"
        #
        ./.github/scripts/diff-output.sh \
          schemacrawler-oracle/src/test/resources/testOraclePortable.txt \
          schemacrawler-hsqldb/src/test/resources/testHsqldbPortableBroad.txt \
          ./diff-output/compare-oracle-hsqldb.html \
          "Compare Oracle - HyperSQL"
        #
        #
        #
        ./.github/scripts/diff-output.sh \
          schemacrawler-oracle/src/test/resources/testOraclePortable.txt \
          schemacrawler-oracle/src/test/resources/testOracleWithConnection.8.txt \
          ./diff-output/oracle-portable-standard.html \
          "Oracle - Portable versus Standard"
        #
        ./.github/scripts/diff-output.sh \
          schemacrawler-sqlserver/src/test/resources/testSQLServerPortable.txt \
          schemacrawler-sqlserver/src/test/resources/testSQLServerWithConnection.8.txt \
          ./diff-output/sqlserver-portable-standard.html \
          "SQL Server - Portable versus Standard"
        #
        ./.github/scripts/diff-output.sh \
          schemacrawler-mysql/src/test/resources/testMySQLPortable.txt \
          schemacrawler-mysql/src/test/resources/testMySQLWithConnection.8.txt \
          ./diff-output/mysql-portable-standard.html \
          "MySQL - Portable versus Standard"
        #
        ./.github/scripts/diff-output.sh \
          schemacrawler-db2/src/test/resources/testDB2Portable.txt \
          schemacrawler-db2/src/test/resources/testDB2WithConnection.8.txt \
          ./diff-output/db2-portable-standard.html \
          "IBM DB2 - Portable versus Standard"
        #
        ./.github/scripts/diff-output.sh \
          schemacrawler-postgresql/src/test/resources/testPostgreSQLPortable.txt \
          schemacrawler-postgresql/src/test/resources/testPostgreSQLWithConnection.8.txt \
          ./diff-output/postgresql-portable-standard.html \
          "PostgreSQL - Portable versus Standard"

    - id: upload-diff-output
      name: Upload diff-output
      uses: actions/upload-artifact@v4
      with:
        name: diff-output
        path: ./diff-output/
        retention-days: 5
