name: Lint Code Base

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 2,16 * *'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:

# CHECKOUT CODE
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v6
      with:
        # Full git history is needed to get a proper list
        # of changed files within `super-linter`
        fetch-depth: 0

# LINT CODE
    - id: read-env
      name: Use super-linter environmental variables
      shell: bash
      run: |
        # Use super-linter environmental variables
        cat .github/super-linter.env >> "$GITHUB_ENV"
    - id: lint-code-base
      name: Lint Code Base
      uses: github/super-linter/slim@v7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: main

# SETUP BUILD ENVIRONMENT
    - id: setup-java
      name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17
        cache: maven
        server-id: sonatype-nexus
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.3

# BUILD
    - id: build
      name: Build and test
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          clean install
