name: Single-Threaded Database Integration Tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '20 20 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    name: Build, run single-threaded database integration tests
    strategy:
      fail-fast: false
      matrix:
        java: [8, 21]
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.5.2
      with:
        java-version: ${{ matrix.java }}
    - id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.3

# BUILD AND TEST
    - id: build-test
      name: Build and run database integration tests
      env:
        TZ: GMT
        SC_SINGLE_THREADED: true
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          clean package
